// client/src/lib/foodFacts.js — rhyming food facts shown during analysis
export const FOOD_FACTS = [
  "An apple a day keeps the doctor away, eat one for breakfast to start your day.",
  "Carrots are crunchy and good for your sight, eat them at lunch or late in the night.",
  "Spinach is green and packed full of iron, eat it with lemon, your body will admire.",
  "Berries are tiny but mighty in might, full of antioxidants, a colorful delight.",
  "Oats in the morning will keep you full longer, a hearty breakfast makes your day stronger.",
  "Bananas have potassium to help your muscles flow, eat one before exercise and watch your energy grow.",
  "Yogurt has cultures that help your gut feel right, a small cup a day keeps your belly light.",
  "Almonds are small but their fats are heart smart, a handful a day is a healthy start.",
  "Sweet potatoes are orange and rich in vitamin A, eat them roasted any night or day.",
  "Garlic may be pungent but it fights off a cold, its healing powers are centuries old.",
  "Broccoli stands tall like a small leafy tree, full of vitamin C for your immunity.",
  "Salmon is pink and rich in good fat, it helps your heart and that's a fact.",
  "Lentils are humble but loaded with fiber, a bowl of dal makes your gut feel livelier.",
  "Avocados are creamy and full of good fat, they're great on toast and that's that.",
  "Walnuts look like brains, a curious sight, they help your own brain think clear and bright.",
  "Beets are deep purple and good for the blood, they boost your stamina more than you would.",
  "Eggs in the morning give protein with ease, a simple breakfast that's sure to please.",
  "Quinoa's a grain that's complete in protein, a hearty side dish that's healthy and lean.",
  "Tomatoes are red with lycopene inside, good for your heart on the fiery side.",
  "Kale may be tough but it's tender with care, full of nutrients beyond compare.",
  "Chickpeas are round and great in a stew, full of fiber to carry you through.",
  "Pumpkin seeds are small but full of zinc, snack on a handful, your body will think.",
  "Blueberries are tiny but brain food indeed, a daily handful is all that you need.",
  "Greek yogurt is thick and protein rich too, a creamy snack that's good for you.",
  "Oranges are juicy with vitamin C, they fight off the cold so you stay free.",
  "Brown rice is hearty and slow to digest, it keeps you fueled and feeling your best.",
  "Cucumbers are cool and mostly just water, they keep you hydrated, no need for slaughter.",
  "Mushrooms are earthy with vitamin D, sauteed in a pan, a tasty decree.",
  "Bell peppers are crunchy in red, green, or yellow, full of vitamin C, a colorful fellow.",
  "Chia seeds swell up when soaked overnight, full of omega threes, a tiny delight.",
  "Pomegranates burst with antioxidant seeds, a jeweled fruit that meets your needs.",
  "Cottage cheese is soft and protein dense, a midnight snack that makes good sense.",
  "Zucchini is mild and low calorie too, spiralize it into noodles for you.",
  "Brussels sprouts are tiny but mighty in fiber, roast them with oil, your taste buds will thrive.",
  "Flaxseed is tiny but full of good fat, sprinkle it on oatmeal, imagine that.",
  "Cauliflower is white and surprisingly grand, mash it like potatoes, a clever new plan.",
  "Strawberries are sweet with vitamin C, a summer treat that's good as can be.",
  "Asparagus is green and a natural diuretic, steam it lightly, the taste is energetic.",
  "Peanut butter is creamy and protein rich, spread on a banana, a satisfying switch.",
  "Black beans are hearty in chili or rice, full of fiber, a budget-friendly choice.",
  "Olive oil drizzled brings heart healthy fat, a Mediterranean staple, simple as that.",
  "Celery is crunchy with very few calories, a perfect snack on your healthy galleries.",
  "Turmeric is golden with anti-inflammatory power, sprinkle it into soup any hour.",
  "Edamame is green in its little pod, full of protein, a plant based nod.",
  "Watermelon is juicy and mostly hydration, perfect for summer rehydration.",
  "Ginger root spices and settles the tummy, brewed into tea it tastes rather yummy.",
  "Cherries are dark and may help you sleep, a few before bed, no counting sheep.",
  "Whole wheat bread has more fiber inside, swap it for white, let your gut be your guide.",
  "Pistachios are green and crunchy delight, a protein packed snack any time of night.",
  "Lean turkey is light and protein forward, great in a sandwich, simple and toward.",
  "Apricots are small and rich in vitamin A, dried or fresh they brighten the day.",
  "Tofu is soft and soaks up the flavor, a plant based protein you'll come to savor.",
  "Cabbage is crunchy and great in a slaw, full of vitamin K, nature's own law.",
  "Grapes are sweet and easy to grab, a frozen handful is a tasty stopgap.",
  "Brown lentil soup warms you up from inside, full of iron with nowhere to hide.",
  "Sardines are small but full of good fat, omega threes packed into something so flat.",
  "Pears are juicy with fiber to spare, a sweet afternoon snack beyond compare.",
  "Hummus is creamy from chickpeas it's made, dip your veggies, a healthy parade.",
  "Spinach smoothies are green and packed full of greens, blend it with fruit for delicious means.",
  "Barley is chewy in soup or in stew, full of fiber that's good for you.",
  "Mangoes are tropical sweet and bright, full of vitamin A, a juicy delight.",
  "Lean ground turkey makes burgers feel light, a leaner choice for your dinner tonight.",
  "Beets roasted bring earthy sweetness in, a vibrant side that's a nutrient win.",
  "Papaya digests with enzymes that aid, a tropical fruit for your gut parade.",
  "Cottage cheese with pineapple's a treat, protein and fruit in one tasty feat.",
  "Almond milk is light if dairy's not for you, calcium fortified to carry you through.",
  "Kiwi is fuzzy but bursting with C, more vitamin power than an orange, you see.",
  "Sunflower seeds crunch with vitamin E, sprinkle on salad for texture and glee.",
  "Whole grain pasta has more fiber than white, swap it tonight for a healthier bite.",
  "Cantaloupe is orange and full of beta carotene, a refreshing fruit, the summer's queen.",
  "Black rice is dark and rich in antioxidant hue, a striking grain that's good for you.",
  "Plain oatmeal with cinnamon spice on the top, a warming breakfast that hits the spot.",
  "Coconut water can hydrate you fast, full of electrolytes, a tropical blast.",
  "Roasted chickpeas crunch like a chip, a protein packed snack worth the dip.",
  "Swiss chard is leafy with vitamin K, a colorful green to brighten your plate.",
  "Trout is a fish that's light on the line, full of good fat, a healthy design.",
  "Dark chocolate in small bits can be a delight, antioxidants present if the cocoa is right.",
  "Radishes are peppery and crunchy and light, a low calorie snack for day or for night.",
  "Lima beans are creamy when cooked nice and slow, full of fiber to help your gut grow.",
  "Green tea is calming with antioxidants too, a warm cup each morning is good for you.",
  "Whole grain crackers with cheese make a snack, balanced and tasty, no need to look back.",
  "Bok choy is tender and great in a stir fry, full of calcium, give it a try.",
  "Red cabbage adds crunch and a colorful hue, slaw with a vinegar dressing for you.",
  "Pumpkin puree in oatmeal or soup, full of fiber in every scoop.",
  "Cod is a fish that's mild and so lean, baked with some lemon, a dinner that's clean.",
  "Snap peas are crunchy and sweet on their own, a perfect raw snack you can eat alone.",
  "Buckwheat is hearty though not wheat at all, gluten free grain that won't let you fall.",
  "Figs are sweet and full of fiber inside, a dried or fresh snack you can't help but bide.",
  "Skim milk is light but still calcium strong, pour it on cereal, you can't go wrong.",
  "Artichokes take work but the reward is so great, full of fiber upon your plate.",
  "Roasted beets with goat cheese on top, a fancy side dish you won't want to stop.",
  "Carrot sticks dipped into hummus with care, a crunchy combo beyond compare.",
  "Whole grain tortillas wrap lunch up just right, more fiber inside for a healthier bite.",
  "Pineapple has bromelain to aid in digestion, a tropical fruit, no health question.",
  "Black eyed peas are hearty in soup or in rice, full of folate, a nutritious device.",
  "Trail mix with nuts and a little dried fruit, energy boosting from root to the shoot.",
  "Bison is lean when it's used in your chili, a leaner red meat, robust but not chilly.",
  "Pearl barley soup warms the soul and the gut, full of fiber in every spoonful you cut.",
  "Seaweed snacks are crunchy and rich in iodine, a salty bite that's healthy and fine.",
  "Whole grain oats topped with berries and seeds, a breakfast bowl that meets all your needs.",
];
