// client/src/lib/foodFacts.js — rhyming food facts shown during analysis
export const FOOD_FACTS = [
  "An apple a day keeps the doctor away, eat one for breakfast to start your day.",
  "Dal is warm and full of protein, eat it with rice for a meal serene.",
  "Carrots are crunchy and good for your sight, eat them at lunch or late in the night.",
  "Roti made of wheat keeps you full and light, pair it with sabzi for a hearty bite.",
  "Spinach is green and packed full of iron, eat it with lemon, your body will admire.",
  "Idli steamed soft and low in fat, a South Indian breakfast, simple as that.",
  "Berries are tiny but mighty in might, full of antioxidants, a colorful delight.",
  "Dosa crisp and thin as lace, filled with potato, a tasty embrace.",
  "Oats in the morning will keep you full longer, a hearty breakfast makes your day stronger.",
  "Sambar is tangy with lentils and spice, a bowl each morning is always nice.",
  "Bananas have potassium to help your muscles flow, eat one before exercise and watch your energy grow.",
  "Rasam is peppery and clears the chest, drink it warm when you need to rest.",
  "Yogurt has cultures that help your gut feel right, a small cup a day keeps your belly light.",
  "Upma is quick from semolina grain, a filling breakfast without much pain.",
  "Almonds are small but their fats are heart smart, a handful a day is a healthy start.",
  "Poha is light and flavored with lime, a flattened rice dish, ready in no time.",
  "Sweet potatoes are orange and rich in vitamin A, eat them roasted any night or day.",
  "Paneer is soft and rich in whey, grill it up for a protein-packed day.",
  "Garlic may be pungent but it fights off a cold, its healing powers are centuries old.",
  "Palak paneer blends greens with cheese, iron and calcium, eaten with ease.",
  "Broccoli stands tall like a small leafy tree, full of vitamin C for your immunity.",
  "Chana is round and packed with fiber, boil it up, your gut will feel livelier.",
  "Salmon is pink and rich in good fat, it helps your heart and that's a fact.",
  "Rajma simmers red in a pot, protein and fiber in every hot spot.",
  "Lentils are humble but loaded with fiber, a bowl of dal makes your gut feel livelier.",
  "Khichdi mixes rice with dal, a comfort bowl that suits us all.",
  "Avocados are creamy and full of good fat, they're great on toast and that's that.",
  "Curd is cool and good for the gut, a small bowl daily keeps you not shut.",
  "Walnuts look like brains, a curious sight, they help your own brain think clear and bright.",
  "Buttermilk churned light and thin, cools the body from deep within.",
  "Beets are deep purple and good for the blood, they boost your stamina more than you would.",
  "Ghee in small spoons aids digestion, a spoonful on dal, no health question.",
  "Eggs in the morning give protein with ease, a simple breakfast that's sure to please.",
  "Turmeric golden fights inflammation, stir it in milk for a warm sensation.",
  "Quinoa's a grain that's complete in protein, a hearty side dish that's healthy and lean.",
  "Ginger root spices up your chai, and settles the stomach, easy to try.",
  "Tomatoes are red with lycopene inside, good for your heart on the fiery side.",
  "Fenugreek seeds called methi in Hindi, bitter at first but good for the body.",
  "Kale may be tough but it's tender with care, full of nutrients beyond compare.",
  "Mustard seeds pop in hot oil with flair, tempering dishes beyond compare.",
  "Chickpeas are round and great in a stew, full of fiber to carry you through.",
  "Amla is sour but rich in vitamin C, a small berry that sets you free.",
  "Pumpkin seeds are small but full of zinc, snack on a handful, your body will think.",
  "Jaggery is sweet in a natural form, better than sugar to keep you warm.",
  "Blueberries are tiny but brain food indeed, a daily handful is all that you need.",
  "Coconut is creamy in curries and rice, healthy fats making meals nice.",
  "Greek yogurt is thick and protein rich too, a creamy snack that's good for you.",
  "Tamarind is tangy in rasam and chutney, a sour twist that isn't too much.",
  "Oranges are juicy with vitamin C, they fight off the cold so you stay free.",
  "Curry leaves fried crisp in oil, add them to dal after it starts to boil.",
  "Brown rice is hearty and slow to digest, it keeps you fueled and feeling your best.",
  "Moong dal is light and easy to digest, a yellow lentil that's simply the best.",
  "Cucumbers are cool and mostly just water, they keep you hydrated, no need for slaughter.",
  "Urad dal thickens dal makhani with care, protein and iron beyond compare.",
  "Mushrooms are earthy with vitamin D, sauteed in a pan, a tasty decree.",
  "Toor dal is common in sambar and dal, a staple pulse loved by all.",
  "Bell peppers are crunchy in red, green, or yellow, full of vitamin C, a colorful fellow.",
  "Besan flour makes cheela thin and gold, a chickpea pancake, savory and bold.",
  "Chia seeds swell up when soaked overnight, full of omega threes, a tiny delight.",
  "Ragi millet is dark and full of calcium, bake it in roti for a strong stomach.",
  "Pomegranates burst with antioxidant seeds, a jeweled fruit that meets your needs.",
  "Jowar roti is gluten free and light, a millet flatbread for a healthy bite.",
  "Cottage cheese is soft and protein dense, a midnight snack that makes good sense.",
  "Bajra roti warms you in winter's chill, paired with jaggery and a little ghee still.",
  "Zucchini is mild and low calorie too, spiralize it into noodles for you.",
  "Brown rice holds its bran and its fiber, cook it slow, your gut will feel livelier.",
  "Brussels sprouts are tiny but mighty in fiber, roast them with oil, your taste buds will thrive.",
  "Basmati rice is fragrant and long, pair with dal for a filling song.",
  "Flaxseed is tiny but full of good fat, sprinkle it on oatmeal, imagine that.",
  "Sprouts are crunchy when moong is soaked, full of protein, lightly cooked.",
  "Cauliflower is white and surprisingly grand, mash it like potatoes, a clever new plan.",
  "Karela is bitter but great for the blood, its sugar-lowering powers more than you would think.",
  "Strawberries are sweet with vitamin C, a summer treat that's good as can be.",
  "Lauki is watery and low in calorie, a bottle gourd curry, light and savory.",
  "Asparagus is green and a natural diuretic, steam it lightly, the taste is energetic.",
  "Bhindi fried dry with turmeric and spice, okra's fiber makes digestion nice.",
  "Peanut butter is creamy and protein rich, spread on a banana, a satisfying switch.",
  "Gobi cauliflower roasted with cumin seed, a low carb veggie that meets your need.",
  "Black beans are hearty in chili or rice, full of fiber, a budget-friendly choice.",
  "Baingan bharta is smoky and mashed, eggplant roasted till the skin is ash.",
  "Olive oil drizzled brings heart healthy fat, a Mediterranean staple, simple as that.",
  "Saag is spinach cooked slow with ghee, iron rich greens for you and me.",
  "Celery is crunchy with very few calories, a perfect snack on your healthy galleries.",
  "Sarson ka saag is mustard green and bold, paired with makki roti when the winter's cold.",
  "Turmeric is golden with anti-inflammatory power, sprinkle it into soup any hour.",
  "Moringa leaves called drumstick tree, full of nutrients, wild and free.",
  "Edamame is green in its little pod, full of protein, a plant based nod.",
  "Jackfruit is fibrous and meat-like too, a great plant swap for a curry or stew.",
  "Watermelon is juicy and mostly hydration, perfect for summer rehydration.",
  "Mango is sweet in summer's heat, rich in vitamin A, a seasonal treat.",
  "Ginger root spices and settles the tummy, brewed into tea it tastes rather yummy.",
  "Guava is crunchy with vitamin C galore, more than an orange, and then some more.",
  "Cherries are dark and may help you sleep, a few before bed, no counting sheep.",
  "Papaya aids digestion after a meal, a tropical fruit that helps you heal.",
  "Whole wheat bread has more fiber inside, swap it for white, let your gut be your guide.",
  "Lassi is thick and churned from curd, a cooling drink, the best you've heard.",
  "Pistachios are green and crunchy delight, a protein packed snack any time of night.",
  "Tandoori chicken is charred and lean, marinated in yogurt, a protein machine.",
  "Lean turkey is light and protein forward, great in a sandwich, simple and toward.",
  "Fish tikka grilled with turmeric and chili, low in fat but never too silly.",
  "Apricots are small and rich in vitamin A, dried or fresh they brighten the day.",
  "Egg bhurji scrambled with onion and spice, a protein breakfast, quick and nice.",
  "Tofu is soft and soaks up the flavor, a plant based protein you'll come to savor.",
  "Roasted chana makes a crunchy snack, full of fiber, keeps hunger back.",
  "Cabbage is crunchy and great in a slaw, full of vitamin K, nature's own law.",
  "Makhana or fox nuts roasted in ghee, a light snack for you and me.",
  "Grapes are sweet and easy to grab, a frozen handful is a tasty stopgap.",
  "Peanuts roasted with a little salt, healthy fats without any fault.",
  "Brown lentil soup warms you up from inside, full of iron with nowhere to hide.",
  "Til or sesame seeds sprinkled with care, add calcium and crunch everywhere.",
  "Sardines are small but full of good fat, omega threes packed into something so flat.",
  "Flaxseed ground fine into your dal, boosts omega threes for one and all.",
  "Pears are juicy with fiber to spare, a sweet afternoon snack beyond compare.",
  "Cashews are creamy in a kheer or curry, eat just a few, there is no hurry.",
  "Hummus is creamy from chickpeas it's made, dip your veggies, a healthy parade.",
  "Pistachios are green and rich in fiber, a handful a day makes snacking livelier.",
  "Spinach smoothies are green and packed full of greens, blend it with fruit for delicious means.",
  "Dates are sweet and a natural sugar, chew a few and skip the sugar bowl figure.",
  "Barley is chewy in soup or in stew, full of fiber that's good for you.",
  "Raisins add sweetness to pulao rice, a small handful, a natural spice.",
  "Mangoes are tropical sweet and bright, full of vitamin A, a juicy delight.",
  "Saunf or fennel seeds chewed after a meal, helps digestion and freshens the zeal.",
  "Lean ground turkey makes burgers feel light, a leaner choice for your dinner tonight.",
  "Ajwain seeds settle a bloated tum, a pinch in dal makes digestion less glum.",
  "Beets roasted bring earthy sweetness in, a vibrant side that's a nutrient win.",
  "Hing or asafoetida added with care, reduces gas in dal beyond compare.",
  "Papaya digests with enzymes that aid, a tropical fruit for your gut parade.",
  "Black pepper adds heat to a rasam pot, and helps you absorb turmeric a lot.",
  "Cottage cheese with pineapple's a treat, protein and fruit in one tasty feat.",
  "Cardamom pods are fragrant and sweet, add them to chai for a cozy treat.",
  "Almond milk is light if dairy's not for you, calcium fortified to carry you through.",
  "Cinnamon sticks simmer slow in chai, balancing blood sugar, easy to try.",
  "Kiwi is fuzzy but bursting with C, more vitamin power than an orange, you see.",
  "Cloves add warmth to a biryani dish, a fragrant spice that grants your wish.",
  "Sunflower seeds crunch with vitamin E, sprinkle on salad for texture and glee.",
  "Bay leaf simmers in dal and rice, adding aroma, subtle and nice.",
  "Whole grain pasta has more fiber than white, swap it tonight for a healthier bite.",
  "Sambar powder blends spices with grace, turning simple veggies into a feast.",
  "Cantaloupe is orange and full of beta carotene, a refreshing fruit, the summer's queen.",
  "Idli batter ferments overnight with yeast, natural probiotics for your gut at least.",
  "Black rice is dark and rich in antioxidant hue, a striking grain that's good for you.",
  "Appam is soft with a lacy crisp edge, made from rice batter on a curved ledge.",
  "Plain oatmeal with cinnamon spice on the top, a warming breakfast that hits the spot.",
  "Uttapam is thick with veggies mixed in, a savory pancake, crispy and thin.",
  "Coconut water can hydrate you fast, full of electrolytes, a tropical blast.",
  "Medu vada is fried but light as air, a lentil doughnut beyond compare.",
  "Roasted chickpeas crunch like a chip, a protein packed snack worth the dip.",
  "Dhokla is steamed, not fried, and light, a Gujarati snack, spongy and bright.",
  "Swiss chard is leafy with vitamin K, a colorful green to brighten your plate.",
  "Thepla is thin with fenugreek leaves, a travel-friendly bread that never grieves.",
  "Trout is a fish that's light on the line, full of good fat, a healthy design.",
  "Paratha stuffed with potato and spice, layered and hot, a breakfast device.",
  "Dark chocolate in small bits can be a delight, antioxidants present if the cocoa is right.",
  "Oats idli swaps rice for a grain, a lighter breakfast without the strain.",
  "Radishes are peppery and crunchy and light, a low calorie snack for day or for night.",
  "Quinoa upma is a modern twist, protein packed and hard to resist.",
  "Lima beans are creamy when cooked nice and slow, full of fiber to help your gut grow.",
  "Vegetable pulao mixes rice with greens, a one-pot meal with vitamins.",
  "Green tea is calming with antioxidants too, a warm cup each morning is good for you.",
  "Dal makhani cooks lentils in butter and cream, a festive dish worth every dream.",
  "Whole grain crackers with cheese make a snack, balanced and tasty, no need to look back.",
  "Chana masala is tangy and bold, chickpeas simmered till the story is told.",
  "Bok choy is tender and great in a stir fry, full of calcium, give it a try.",
  "Rajma chawal pairs beans with rice, a classic combo that's always nice.",
  "Red cabbage adds crunch and a colorful hue, slaw with a vinegar dressing for you.",
  "Kadhi is tangy from yogurt and gram, a soothing bowl, however you cram.",
  "Pumpkin puree in oatmeal or soup, full of fiber in every scoop.",
  "Curd rice cools a spicy meal down, mix it with pickle, a comforting crown.",
  "Cod is a fish that's mild and so lean, baked with some lemon, a dinner that's clean.",
  "Tamarind rice is tangy and bright, a South Indian lunch, packed just right.",
  "Snap peas are crunchy and sweet on their own, a perfect raw snack you can eat alone.",
  "Lemon rice is zesty and quick to make, a citrusy dish for a lunchbox to take.",
  "Buckwheat is hearty though not wheat at all, gluten free grain that won't let you fall.",
  "Coconut chutney pairs well with dosa, ground fresh each morning, never a bore.",
  "Figs are sweet and full of fiber inside, a dried or fresh snack you can't help but bide.",
  "Mint chutney is cooling and green, refreshes the palate, keeps breath clean.",
  "Skim milk is light but still calcium strong, pour it on cereal, you can't go wrong.",
  "Coriander chutney is tangy and fresh, blended with chili for a flavorful mesh.",
  "Artichokes take work but the reward is so great, full of fiber upon your plate.",
  "Papad roasted, not fried, is best, a crispy side that aids in digest.",
  "Roasted beets with goat cheese on top, a fancy side dish you won't want to stop.",
  "Fish curry simmers in coconut milk, a coastal dish, smooth as silk.",
  "Carrot sticks dipped into hummus with care, a crunchy combo beyond compare.",
  "Chicken curry slow cooked with spice, a Sunday meal that's always nice.",
  "Whole grain tortillas wrap lunch up just right, more fiber inside for a healthier bite.",
  "Egg curry simmers in onion and tomato, protein rich in every ladle-o.",
  "Pineapple has bromelain to aid in digestion, a tropical fruit, no health question.",
  "Paneer tikka grilled on skewers with char, a vegetarian protein that goes far.",
  "Black eyed peas are hearty in soup or in rice, full of folate, a nutritious device.",
  "Sprouts chaat mixes moong with lime, a crunchy snack, ready in no time.",
  "Trail mix with nuts and a little dried fruit, energy boosting from root to the shoot.",
  "Fruit chaat mixes seasonal fruit with chaat masala spice, a tangy treat that's always nice.",
  "Bison is lean when it's used in your chili, a leaner red meat, robust but not chilly.",
  "Haldi doodh or turmeric milk at night, soothes the body before you sleep tight.",
  "Pearl barley soup warms the soul and the gut, full of fiber in every spoonful you cut.",
  "Ginger tea warms you on a rainy day, and settles the stomach along the way.",
  "Seaweed snacks are crunchy and rich in iodine, a salty bite that's healthy and fine.",
  "Coconut water hydrates after the heat, a natural drink that can't be beat.",
  "Whole grain oats topped with berries and seeds, a breakfast bowl that meets all your needs.",
  "Sabudana khichdi is chewy and light, a fasting favorite any day or night.",
];
